### ISSUE TITLE
Progress Tracker for Students

### ISSUE THREAD

**Issue by slickwarren** [asidanceelite/asi-documentation#6]
- [ ] create list of all requirements across all classes and levels
- [x] create first draft of https://progress.asi.dance
- [x] create first draft of backend for website
